#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2026 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
prepare_service
SERVICE_NAME="matomo"
check_service_initialized init 10-unit

sanity_db
db_ready mariadb

if [ ! -f "${UNIT_WEBROOT}"/index.php ]; then
        print_warn "No Matomo Installation Found, Installing..."
        mkdir -p "${UNIT_WEBROOT}"
        curl -sSL https://builds.matomo.org/piwik-latest.tar.gz | tar xfz - --strip 1 -C "${UNIT_WEBROOT}"
        curl -sSL https://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz | gunzip -c > "${UNIT_WEBROOT}"/misc/GeoIPCity.dat
        print_info "Install Complete"
fi

echo "*/${CRON_PERIOD} * * * * sudo -u ${UNIT_USER} TZ=${TIMEZONE} php ${UNIT_WEBROOT}/console core:archive >/dev/null 2>&1" | silent tee /container/cron/matomo_archive_reports
echo "alias console='cd ${UNIT_WEBROOT}; sudo -u ${UNIT_USER} php ./console'" | silent tee -a /root/.bashrc
chown -R "${UNIT_USER}":"${UNIT_GROUP}" "${UNIT_WEBROOT}"

liftoff
